version: '3.1'

services:
  db:
    image: postgres
    container_name: 'pg'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root

  redis:
    image: redis
    ports:
      - 6379:6379
