name: deployment

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: test
        run: echo it is a test
      - name: ls
        run: ls

  deployment:
    needs: [test]
    runs-on: "ubuntu-latest"
    steps:
      - name: Build and Push to docker hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: marefati110/mole-backend
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
