name: deployment

on:
  push:
    branches:
      - "main"

jobs:
  deployment:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        name: Check out code
    
      - name: Build and Push to docker hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: marefati110/mole-backend
          registry: docker.io
          directory: "."
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
